### ISSUE TITLE
Better landing page

### ISSUE THREAD

**Issue by wavebeem** [squiggle-lang/squiggle-lang.org#3]
The landing page should describe the language goals and core principles.

Also maybe a fun analogy about how Squiggle is like sugar for JS but it's actually good, not just superficial. Something that captures the spirit of this, without referencing CoffeeScript:

"If CoffeeScript is sugar, Squiggle is a gummy vitamin"

**Comment by deleteme** [comment]
I was going to suggest this, but it looks like you're already well aware of the need. Before diving in to API docs, I wish I read about the underlying philosophy of squiggle, and why it would be a good choice for any program.

**Comment by wavebeem** [comment]
@deleteme Yup. It's one of those less glorious and "more-or-less entirely in my head" things. But certainly worth writing down.

I think maybe a quick bit about my overall feelings on the project would be good...

> Squiggle makes JavaScript stricter and simpler. It is expression oriented and actively discourages mutation. It is influenced by Python, Clojure, Lua, Haskell, and more. JavaScript interop is essentially free because Squiggle does not introduce new datatypes. Squiggle is a simple to-JavaScript transpiler, and does not introduce a new build system or new package manager. Squiggle is a language optimized for humans. It is intended to be helpful (by throwing errors) and powerful (by including features JS does not) before it is meant to be fast.

And then maybe a teaser of the useful features in Squiggle:
- Arity checked functions
- Named-this
- Slurpy arguments [FIXME: need a better name for this]
- ES2015-style temporal deadzone on variables
- Immutable array/object literals
- Operators for concatenation and object updates
- Pattern matching
- Stricter binary operators
- ES2015-style shorthand object literals: `{foo}` means `{foo: foo}`
- Concise function syntax: `fn(x, y) x + y`
- Easier errors: `error "oopsy"` vs `throw new Error("oopsy")`
- `try` as an expression: `match try foo(x) case ["ok", v] => ... case ["fail", e] => ... end`
- `foo.bar` throws an exception unless `'bar' in foo` is true
- `==` provides a deep equality check
