### ISSUE TITLE
Explain the '~' operator

### ISSUE THREAD

**Issue by LucianBuzzo** [squiggle-lang/squiggle-lang.org#34]
On the tutorial page on literals (http://squiggle-lang.org/tutorial/chapter/2.5/) is the following line:

> Making new objects with updated properties is done via the ~ operator covered later.

However I don't believe that this operator is ever covered in the tutorial.

**Comment by wavebeem** [comment]
Thanks. I thought I covered that next to `++` in chapter 2.6, but it's totally not there.
